### ISSUE TITLE
missing Home Assistant .exe . Solved

### ISSUE THREAD

**Issue by DaHype** [LxonWWW/Home-Assistant-Desktop-WF#1]
Sorry for post here but i cant install it, because i don´t have Home Assistant.exe in the Zip folder.
Which file i have to use for create an Shortcut?

Thank you

**Comment by LxonWWW** [comment]
It looks like you downloaded the project files. For the latest precompiled release check out:
https://github.com/LxonWWW/Home-Assistant-Desktop-WF/releases/ (Home_Assistant_Desktop_WF.zip)

![grafik](https://github.com/LxonWWW/Home-Assistant-Desktop-WF/assets/29819445/c7693e2c-ef1b-4bf6-b280-6d8441b11319)

I have marked the .exe file in the picture.

**Comment by DaHype** [comment]
Oh sorry, you are totaly right. I downloaded the wrong zip. Thats my fault. Sorry :-(
